### ISSUE TITLE
Energy-based criterion in current version of Peridigm 

### ISSUE THREAD

**Issue by maxincrease** [PeriDoX/PeriDoX#3]
Dear developers,

Unfortunately, I didn't manage to build the newest version of peridigm with your Energy-based criterion code. Could you tell me please, do you dispose a newer version of the code, which is compatible with the newest version of peridigm? If not, is it supposed to be updated in the near future? 

Thanks!

Maksim.

**Comment by CWillberg** [comment]
Dear Maksim,

I created an extra branch for this reason

https://github.com/PeriDoX/peridigm


Best regards
Christian

Von: maxincrease [mailto:notifications@github.com]
Gesendet: Donnerstag, 24. Oktober 2019 08:11
An: PeriDoX/PeriDoX
Cc: Subscribed
Betreff: [PeriDoX/PeriDoX] Energy-based criterion in current version of Peridigm (#3)


Dear developers,

Unfortunately, I didn't manage to build the newest version of peridigm with your Energy-based criterion code. Could you tell me please, do you dispose a newer version of the code, which is compatible with the newest version of peridigm? If not, is it supposed to be updated in the near future?

Thanks!

Maksim.

**Comment by maxincrease** [comment]
Dear Christian,

I found that with Gaussian influence function energy-based criterion gives improper energy release rate for the running crack (I calculated it using J-Integral in quasi-static case). With influence function, that's equal to One it's ok. Is this code intended for using with Gaussian function as well?

Thank you!

Maksim.

**Comment by CWillberg** [comment]
Dear Maksim,

I think I understand what you mean. Right now I have no intention. However, feel free to extent the code. If you need help please contact me. We can also speak in a telco an discuss the code with a shared screen if needed.


Best regards
Christian

German Aerospace Center (DLR)
Institute of Composite Structures and Adaptive Systems | Structural Mechanics | Lilienthalplatz 7 | 38108 Braunschweig
Dr.-Ing. Christian Willberg
Telefon +49 (0)531 295-2489 | Fax +49 (0)531 295-2232 | christian.willberg@dlr.de<mailto:christian.willberg@dlr.de>
www.DLR.de/FA<http://www.dlr.de/FA> | leichtbau.dlr.de



Von: maxincrease [mailto:notifications@github.com]
Gesendet: Freitag, 10. April 2020 16:45
An: PeriDoX/PeriDoX
Cc: Willberg, Christian; Comment
Betreff: Re: [PeriDoX/PeriDoX] Energy-based criterion in current version of Peridigm (#3)


Dear Christian,

I found that with Gaussian influence function energy-based criterion gives improper energy release rate for the running crack (I calculated it using J-Integral in quasi-static case). With influence function, that's equal to One it's ok. Is this code intended for using with Gaussian function as well?

Thank you!

Maksim.

**Comment by oldninja** [comment]
Hello @CWillberg, I was trying to compile the branch in [https://github.com/PeriDoX/peridigm](https://github.com/PeriDoX/peridigm). However, I got the following build error [https://pastebin.com/wHHu1MAD](https://pastebin.com/wHHu1MAD). I noticed in some of the files that there were some boost library dependencies, but if I remember correctly those were removed in the master branch of peridigm (please correct me if I'm wrong). Do I need the boost dependencies to build the energy-based criterion branch? or do you suggest another approach? I installed the latest peridigm master without the boost library.

Look forward to hearing back from you :) Thank you so much for your contribution!

**Comment by CWillberg** [comment]
Unfortunately with newest Version the uploaded energy criterion won’t work.  I think you have to use version 1.5.1. I made an update a few months back. But I did not have the time to upload it.

Christian

Von: oldninja <notifications@github.com>
Gesendet: Sonntag, 8. November 2020 08:28
An: PeriDoX/PeriDoX <PeriDoX@noreply.github.com>
Cc: Willberg, Christian <Christian.Willberg@dlr.de>; Mention <mention@noreply.github.com>
Betreff: Re: [PeriDoX/PeriDoX] Energy-based criterion in current version of Peridigm (#3)


Hello @CWillberg<https://github.com/CWillberg>, I was trying to compile the branch in https://github.com/PeriDoX/peridigm. However, I got the following build error https://pastebin.com/wHHu1MAD. I noticed in some of the files that there were some boost library dependencies, but if I remember correctly those were removed in the master branch of peridigm (please correct me if I'm wrong). Do I need the boost dependencies to build the energy-based criterion branch? or do you suggest another approach? I installed the latest peridigm master without the boost library.

Look forward to hearing back from you :) Thank you so much for your contribution!

**Comment by oldninja** [comment]
@CWillberg thank you so much for your quick reply! 
Sure, I understand. I just started working on trying to make it work for the current master version (1.5.0 dev), but if you find time to upload the changes you made I would greatly appreciate it! - As you may know, there have been numerous commits with many changes to the master branch.
Once again, thank you for your time and help!

**Comment by CWillberg** [comment]
@oldninja The update has been made. You can find the new version under code/anisotropic

**Comment by CWillberg** [comment]
@maxincrease The update has been made. You can find the new version under code/anisotropic

**Comment by CWillberg** [comment]
It took a very long time. Our current developments can be found here.

https://github.com/PeriHub

 

Von: oldninja ***@***.***> 
Gesendet: Dienstag, 10. November 2020 08:20
An: PeriDoX/PeriDoX ***@***.***>
Cc: Willberg, Christian ***@***.***>; Mention ***@***.***>
Betreff: Re: [PeriDoX/PeriDoX] Energy-based criterion in current version of Peridigm (#3)

 

@CWillberg <https://github.com/CWillberg>  thank you so much for your quick reply!
Sure, I understand. I just started working on trying to make it work for the current master version (1.5.0 dev), but if you find time to upload the changes you made I would greatly appreciate it! - As you may know, there have been numerous commits with many changes to the master branch.
Once again, thank you for your time and help!
