### ISSUE TITLE
Replicate load-displacement curve for GAMM2018 presentation

### ISSUE THREAD

**Issue by oldninja** [PeriDoX/PeriDoX#4]
Dear developers,

First of all, thank you so much for your efforts in putting together this repo!

I've been working on trying to port the critical energy damage model into the current master version of [Peridigm (1.5.0 dev)](https://github.com/peridigm/peridigm) and one of the benchmark problems that I was trying to use for this was the DCB model in the [GAMM 2018 presentation](https://github.com/PeriDoX/PeriDoX/blob/master/Publications/2018_GAMM/Presentation/WillbergC_An_energy_based_peridynamic_state_based_failure_criterion_GAMM2018.pdf). However, I have not been able to: 
1. Accurately reproduce the load-displacement curve on slide 22. The results I get for the peak load are about 1N lower than the published results, around 4.2 ~ 4.6 N depending on the mesh refinement.
2. The damage contours on slide 21. Only the coarse mesh (0.5 mm) models showed the damage as in slide 21. The refined models did not show this behavior, only a crack through the entire length (no branching).

The process I followed to build was this:
1. Used [Peridigm (1.5.0 dev)](https://github.com/peridigm/peridigm) as baseline.
2. Used [PeriDoX's forked Peridigm](https://github.com/PeriDoX/peridigm) to include the critical energy damage model files.
3. Used the [PeriDoX's Development Guide](https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Development_Guide/Peridigm_Development_Guide.pdf) to follow the necessary changes and compare to the 1. above.

I definitely cannot rule out user error on my end. 
I tried the "out-of-box" master peridigm, and I still get the same results for the critical stretch models, so I wonder if something significantly changed between versions or if I'm not running the same models (in terms of actual values in the input deck).
I would really appreciate any guidance here if possible.

- Coarser mesh model:
<img src="https://user-images.githubusercontent.com/49734546/105743089-4c56ca00-5f0a-11eb-8460-e53a501a0fcb.png" width=47% /> <img src="https://user-images.githubusercontent.com/49734546/105743097-4d87f700-5f0a-11eb-8076-cb88bb2adbec.png" width=50% />

- Finer mesh model:
<img src="https://user-images.githubusercontent.com/49734546/105743049-41039e80-5f0a-11eb-8f30-bdfc7bf173bd.png" width=47% /> <img src="https://user-images.githubusercontent.com/49734546/105743077-49f47000-5f0a-11eb-8387-0c9649628a89.png" width=50% />

**Comment by CWillberg** [comment]
Hello.

I will have a look in 2 weeks. Before that I won’t have time.

Best regards
Christian

Von: oldninja <notifications@github.com>
Gesendet: Montag, 25. Januar 2021 19:13
An: PeriDoX/PeriDoX <PeriDoX@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: [PeriDoX/PeriDoX] Replicate load-displacement curve for GAMM2018 presentation (#4)


Dear developers,

First of all, thank you so much for your efforts in putting together this repo!

I've been working on trying to port the critical energy damage model into the current master version of Peridigm (1.5.0 dev)<https://github.com/peridigm/peridigm> and one of the benchmark problems that I was trying to use for this was the DCB model in the GAMM 2018 presentation<https://github.com/PeriDoX/PeriDoX/blob/master/Publications/2018_GAMM/Presentation/WillbergC_An_energy_based_peridynamic_state_based_failure_criterion_GAMM2018.pdf>. However, I have not been able to:

  1.  Accurately reproduce the load-displacement curve on slide 22. The results I get for the peak load are about 1N lower than the published results, around 4.2 ~ 4.6 N depending on the mesh refinement.
  2.  The damage contours on slide 21. Only the coarse mesh (0.5 mm) models showed the damage as in slide 21. The refined models did not show this behavior, only a crack through the entire length (no branching).

The process I followed to build was this:

  1.  Used Peridigm (1.5.0 dev)<https://github.com/peridigm/peridigm> as baseline.
  2.  Used PeriDoX's forked Peridigm<https://github.com/PeriDoX/peridigm> to include the critical energy damage model files.
  3.  Used the PeriDoX's Development Guide<https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Development_Guide/Peridigm_Development_Guide.pdf> to follow the necessary changes and compare to the 1. above.

I definitely cannot rule out user error on my end.
I tried the "out-of-box" master peridigm, and I still get the same results for the critical stretch models, so I wonder if something significantly changed between versions or if I'm not running the same models (in terms of actual values in the input deck).
I would really appreciate any guidance here if possible.

  *   Coarser mesh model:
[https://user-images.githubusercontent.com/49734546/105743089-4c56ca00-5f0a-11eb-8460-e53a501a0fcb.png]<https://user-images.githubusercontent.com/49734546/105743089-4c56ca00-5f0a-11eb-8460-e53a501a0fcb.png>[https://user-images.githubusercontent.com/49734546/105743097-4d87f700-5f0a-11eb-8076-cb88bb2adbec.png]<https://user-images.githubusercontent.com/49734546/105743097-4d87f700-5f0a-11eb-8076-cb88bb2adbec.png>
  *   Finer mesh model:
[https://user-images.githubusercontent.com/49734546/105743049-41039e80-5f0a-11eb-8f30-bdfc7bf173bd.png]<https://user-images.githubusercontent.com/49734546/105743049-41039e80-5f0a-11eb-8f30-bdfc7bf173bd.png>[https://user-images.githubusercontent.com/49734546/105743077-49f47000-5f0a-11eb-8387-0c9649628a89.png]<https://user-images.githubusercontent.com/49734546/105743077-49f47000-5f0a-11eb-8387-0c9649628a89.png>

**Comment by jritta** [comment]
@oldninja 
That's interesting, did you compare the master of Peridigm with the master version they used (It is [written](https://github.com/PeriDoX/PeriDoX/blob/master/Peridigm/Code/Energy_damage_criterion/ReadMe.txt) that they tested it with the master of 19/12/2017). Maybe you can find out if there are major changes which could maybe influence the result...

**Comment by oldninja** [comment]
@jritta 
No, I used the fork in the [PeriDoX](https://github.com/PeriDoX/peridigm) account. I believe that was the latest version based on [this](https://github.com/PeriDoX/PeriDoX/issues/3#issuecomment-546725103) issue, but I could be wrong.

**Comment by CWillberg** [comment]
I did the update today. Hopefully it works fine for you.

Von: oldninja ***@***.***>
Gesendet: Montag, 25. Januar 2021 19:13
An: PeriDoX/PeriDoX ***@***.***>
Cc: Subscribed ***@***.***>
Betreff: [PeriDoX/PeriDoX] Replicate load-displacement curve for GAMM2018 presentation (#4)


Dear developers,

First of all, thank you so much for your efforts in putting together this repo!

I've been working on trying to port the critical energy damage model into the current master version of Peridigm (1.5.0 dev)<https://github.com/peridigm/peridigm> and one of the benchmark problems that I was trying to use for this was the DCB model in the GAMM 2018 presentation<https://github.com/PeriDoX/PeriDoX/blob/master/Publications/2018_GAMM/Presentation/WillbergC_An_energy_based_peridynamic_state_based_failure_criterion_GAMM2018.pdf>. However, I have not been able to:

  1.  Accurately reproduce the load-displacement curve on slide 22. The results I get for the peak load are about 1N lower than the published results, around 4.2 ~ 4.6 N depending on the mesh refinement.
  2.  The damage contours on slide 21. Only the coarse mesh (0.5 mm) models showed the damage as in slide 21. The refined models did not show this behavior, only a crack through the entire length (no branching).

The process I followed to build was this:

  1.  Used Peridigm (1.5.0 dev)<https://github.com/peridigm/peridigm> as baseline.
  2.  Used PeriDoX's forked Peridigm<https://github.com/PeriDoX/peridigm> to include the critical energy damage model files.
  3.  Used the PeriDoX's Development Guide<https://github.com/PeriDoX/PeriDoX/blob/master/Doc/Peridigm_Development_Guide/Peridigm_Development_Guide.pdf> to follow the necessary changes and compare to the 1. above.

I definitely cannot rule out user error on my end.
I tried the "out-of-box" master peridigm, and I still get the same results for the critical stretch models, so I wonder if something significantly changed between versions or if I'm not running the same models (in terms of actual values in the input deck).
I would really appreciate any guidance here if possible.

  *   Coarser mesh model:
[Das Bild wurde vom Absender entfernt.]<https://user-images.githubusercontent.com/49734546/105743089-4c56ca00-5f0a-11eb-8460-e53a501a0fcb.png>[Das Bild wurde vom Absender entfernt.]<https://user-images.githubusercontent.com/49734546/105743097-4d87f700-5f0a-11eb-8076-cb88bb2adbec.png>
  *   Finer mesh model:
[Das Bild wurde vom Absender entfernt.]<https://user-images.githubusercontent.com/49734546/105743049-41039e80-5f0a-11eb-8f30-bdfc7bf173bd.png>[Das Bild wurde vom Absender entfernt.]<https://user-images.githubusercontent.com/49734546/105743077-49f47000-5f0a-11eb-8387-0c9649628a89.png>

**Comment by oldninja** [comment]
Thank you @CWillberg! I will give it a try later today!

**Comment by oldninja** [comment]
@CWillberg I compiled the current master of [peridigm (1.5.0 dev)](https://github.com/peridigm/peridigm)- compiled fine. Then I proceeded to follow the instructions on the [ReadMe](https://github.com/PeriDoX/PeriDoX/blob/master/Peridigm/Code/Anisotropic_Material/ReadMe.txt) file to compile but this error appeared:

```
$ ./peridigm_source/src/core/Peridigm.cpp:573:49: error: ‘class PeridigmNS::Discretization’ has no member named ‘getPointAngle’
  573 |     blockIt->importData(peridigmDiscretization->getPointAngle(),   anglesFieldId, PeridigmField::STEP_NONE, Insert);
```
Which version of Peridigm should I be using? I assumed it was a drop-in change.

**Comment by CWillberg** [comment]
It is in the drop-in change. I think the issue here is, that the changes in the discretization routines I made are older than your downloaded files. You have to delete your compiled version and build it from the scratch. This is because only if files are newer (that is the definition of different in this case) are compiled.

Christian
Von: oldninja ***@***.***>
Gesendet: Mittwoch, 14. April 2021 02:38
An: PeriDoX/PeriDoX ***@***.***>
Cc: Willberg, Christian ***@***.***>; Mention ***@***.***>
Betreff: Re: [PeriDoX/PeriDoX] Replicate load-displacement curve for GAMM2018 presentation (#4)


@CWillberg<https://github.com/CWillberg> I compiled the current master of peridigm (1.5.0 dev)<https://github.com/peridigm/peridigm>- compiled fine. Then I proceeded to follow the instructions on the ReadMe<https://github.com/PeriDoX/PeriDoX/blob/master/Peridigm/Code/Anisotropic_Material/ReadMe.txt> file to compile but this error appeared:

$ ./peridigm_source/src/core/Peridigm.cpp:573:49: error: ‘class PeridigmNS::Discretization’ has no member named ‘getPointAngle’



  573 |     blockIt->importData(peridigmDiscretization->getPointAngle(),   anglesFieldId, PeridigmField::STEP_NONE, Insert);



Which version of Peridigm should I be using? I assumed it was a drop-in change.

**Comment by oldninja** [comment]
Hi @CWillberg, I cleaned up the build directories and everything, but no luck. Maybe there is something missing on the update files? See the attached diff: compared the files from the anisotropic folder to the ones copied to the src folder. They are identical.

[Compared.pdf](https://github.com/PeriDoX/PeriDoX/files/6489731/Compared.pdf)

Thanks again for your time!
