### ISSUE TITLE
Compile error——anisotropy

### ISSUE THREAD

**Issue by DP52** [PeriDoX/PeriDoX#7]
Dear developers,

I 'd like to use the anisotropic module you wrote, but there are also the following problems in the compilation process :
/home/dp/peridigm/pd/peridigm-master/src/core/Peridigm.cpp:573:49: error: ‘class PeridigmNS::Discretization’ has no member named ‘getPointAngle’

And I tried to delete the original compiled peridigm, rebuild it, but still can 't.

So how to solve this problem ? Need your help very much, thank you !

**Comment by CWillberg** [comment]
Hello,

we have a working version here. 

https://github.com/PeriHub/Peridigm/

All the best
Christian
